name: Techvisit Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean package -DskipTests -e

      - name: List target directory
        run: ls -l target/

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/techvisit .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/techvisit

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/techvisit:latest

      - name: Remove existing Docker container
        run: |
          if [ $(sudo docker ps -a -q -f name=techvisit) ]; then
            sudo docker rm -f techvisit
          fi

      - name: Run Docker container
        run: |
          sudo docker run -d -p 8080:8080 \
          -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --name techvisit ${{ secrets.DOCKER_USERNAME }}/techvisit:latest
